### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory on player dispose

### ISSUE THREAD

**Issue by dilandau2001** [ZeBobo5/Vlc.DotNet#346]
I have an issue about Vlc.DotNet.

# Generic information

- **Vlc.DotNet version** : master branch September 2017 framework 4.5
- **Vlc.DotNet project used** : Forms
- **libvlc version** :  2.2.5.1 - VLC 2.2.6 Umbrella
- **.net version** : 4.6.2
- **Project language** : (C#) 
- **Project build architecture** : (x86)
- **Operating system** : (Windows 7)

# Summary
In my application I allow to "drag and drop" multiple players to a "canvas" of players. The user can open and close the players at will.
Sometimes when a player is closed I receive the following error and the application crashes (even with a try catch the application just dies):

```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Vlc.DotNet.Core.Interops.VlcManager.ReleaseMediaPlayer(VlcMediaPlayerInstance mediaPlayerInstance) in D:\PROYECTOS\C2017\Vlc.dotNet\Vlc.DotNet-master\src\Vlc.DotNet.Core.Interops\VlcManager.ReleaseMediaPlayer.cs:line 14
   at Vlc.DotNet.Core.Interops.VlcMediaPlayerInstance.Dispose(Boolean disposing) in D:\PROYECTOS\C2017\Vlc.dotNet\Vlc.DotNet-master\src\Vlc.DotNet.Core.Interops\VlcMediaPlayerInstance.cs:line 18
   at Vlc.DotNet.Core.Interops.Signatures.InteropObjectInstance.Finalize() in D:\PROYECTOS\C2017\Vlc.dotNet\Vlc.DotNet-master\src\Vlc.DotNet.Core.Interops\Signatures\InteropObjectInstance.cs:line 33
   at Vlc.DotNet.Core.Interops.VlcManager.ReleaseMediaPlayer(VlcMediaPlayerInstance mediaPlayerInstance) in D:\PROYECTOS\C2017\Vlc.dotNet\Vlc.DotNet-master\src\Vlc.DotNet.Core.Interops\VlcManager.ReleaseMediaPlayer.cs:line 14
   at Vlc.DotNet.Core.Interops.VlcMediaPlayerInstance.Dispose(Boolean disposing) in D:\PROYECTOS\C2017\Vlc.dotNet\Vlc.DotNet-master\src\Vlc.DotNet.Core.Interops\VlcMediaPlayerInstance.cs:line 18
   at Vlc.DotNet.Core.Interops.Signatures.InteropObjectInstance.Finalize() in D:\PROYECTOS\C2017\Vlc.dotNet\Vlc.DotNet-master\src\Vlc.DotNet.Core.Interops\Signatures\InteropObjectInstance.cs:line 33
```

this is the code from designer partial class that calls dispose of the player:

```
partial class Viewer
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;
        private VlcControl _vlcControl;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                this.UnhookEvents();

                // Dispose video player
                if (this._vlcControl != null)
                {
                    this.Controls.Remove(this._vlcControl);

                    try
                    {
                        this._vlcControl.Dispose();
                    }
                    catch (AccessViolationException exception)
                    {
                        this._traceHelper.TraceWarning(
                            "VlcViewer->Dispose: Vlc.dotNet send an exception during viewer disposal: " +
                            exception.Message);
                    }
                    catch (Exception exception)
                    {
                        this._traceHelper.TraceError(
                            "VlcViewer->Dispose: Vlc.dotNet send an exception during viewer disposal: " +
                            exception.Message);
                    }
                    
                    this._vlcControl = null;
                }

                components.Dispose();
            }

            try
            {
                base.Dispose(disposing);
            }
            catch (AccessViolationException exception)
            {
                this._traceHelper.TraceWarning("VlcViewer->Dispose: Vlc.dotNet send an exception during viewer disposal: " + exception.Message);
            }
            
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        }

        #endregion
    }
```

- [x ] I confirm that my issue doesn't happen in VLC itself.

**Comment by jeremyVignelles** [comment]
Hi,
Thanks for reporting. Indeed, I think something is wrong with the Dispose method because this is not the first time an issue is reported for that method (see #237).
Will have a look into it.

**Comment by jeremyVignelles** [comment]
Does this issue still happen with libvlc 3.0 and Vlc.DotNet 3.0?

**Comment by jacuff** [comment]
I see something similar whenever I call Dispose().  

Exception thrown: 'System.AccessViolationException' in Vlc.DotNet.Core.Interops.dll
An unhandled exception of type 'System.AccessViolationException' occurred in Vlc.DotNet.Core.Interops.dll
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

VideoLAN.LibVLC.Windows version="3.0.0-alpha3" targetFramework="net471"
Vlc.DotNet.Core version="3.0.0-develop289" targetFramework="net471"
Vlc.DotNet.Core.Interops version="3.0.0-develop289" targetFramework="net471"
Vlc.DotNet.Forms version="3.0.0-develop289" targetFramework="net471"
Vlc.DotNet.Wpf version="3.0.0-develop289" targetFramework="net471"

**Comment by jeremyVignelles** [comment]
Are you disposing on the main thread? (you should, as far as I remember)

**Comment by jacuff** [comment]
Yes, it is calling the Dispose() method from Main Thread. Basically, I have a WPF form that will place  Rows (R) x  Columns (C) number of VlcControls on a gird. If RxC is reduced by the user through a , I call a function that basically does this.

```C#
private static int gridRows = Settings.Default.gridRows;
private static int gridColumns = Settings.Default.gridColumns;
private VlcControl[,] vlcControls = new VlcControl[gridRows, gridColumns];

private void MenuItemSettings_Click(object sender, RoutedEventArgs e){
    SettingsDialog settings = new SettingsDialog();
    Nullable<bool> result = settings.ShowDialog();

    if (result == true){
        gridRowsTransposed = Settings.Default.gridRows;
        gridColumnsTransposed = Settings.Default.gridColumns;
        RemoveUnneededPlayers(gridRows, gridColumns, gridRowsTransposed, gridColumnsTransposed);
    }
}

private void RemoveUnneededPlayers(int oldR, int oldC, int newR, int newC){
    int oldSize = oldR * oldC;
    int newSize = newR * newC;
    int i = 0;
    if (oldSize > newSize){
        for(int r = 0; r < oldR; r++){
            for(int c = 0; c < oldC; c++){
                // Loop through the array and dispose players no longer needed.
                if(i >= newSize){
                    vlcControls[r,c].SourceProvider.MediaPlayer.EndReached -= OnMediaPlayerEndReached;
                    vlcControls[r,c].Dispose();    // If I remove this line, it works but the memory isn't freed.
                    vlcControls[r.c] = null;       // This doesn't help to free memory either.
                }
            }
        }
    }
}

**Comment by jeremyVignelles** [comment]
Do you also create them in the main thread?

**Comment by jacuff** [comment]
Yes, the are also created on the Main Thread. Here's additional applicable code
```C#
private readonly DirectoryInfo vlcLibDirectory;
private string[] vlcMediaPlayerOptions = { };

public MainWindowVlc(){
    InitializeComponent();
    var currentAssembly = Assembly.GetEntryAssembly();
    var currentDirectory = new FileInfo(currentAssembly.Location).DirectoryName;
    vlcLibDirectory = new DirectoryInfo(Path.Combine(currentDirectory, "libvlc", IntPtr.Size == 4 ? "win-x86" : "win-x64"));
    InitializeVariables();
}

private void InitializeVariables(){
    for (int r = 0; r < gridRows; r++){
        for (int c = 0; c < gridColumns; c++){
            VlcControl vlcControl = new VlcControl();
            vlcControl.SourceProvider.CreatePlayer(vlcLibDirectory, vlcMediaPlayerOptions);
            vlcControl.Uid = Guid.NewGuid().ToString();
            vlcControl.SourceProvider.MediaPlayer.EndReached += OnMediaPlayerEndReached;
            vlcControl.SourceProvider.MediaPlayer.Audio.Volume = 0;
            vlcControls[r, c] = vlcControl;
        }
    }
}

**Comment by chickentech** [comment]
I'm also having a similar issue on 3.0.0 develop 296
using vlc 3.0.3 libs and plugins.

**Comment by chickentech** [comment]
latest 3.0.0-develop306 fixes this crash on dispose for me.

**Comment by jeremyVignelles** [comment]
I don't see any good reason why any commit between your two versions would fix your issue...

**Comment by chickentech** [comment]
@jeremyVignelles you're right - it still happens.  Just not always consistently crashes.

**Comment by jeremyVignelles** [comment]
@dilandau2001, @chickentech : do you confirm that this issue is fixed since latest develop package?

**Comment by dilandau2001** [comment]
I would be not fair to me to say that is fixed as I am the one that did the pull ;-).

What I can confirm is that I am no longer able to reproduce it with these changes.

Also note that the changes in the pull #477 make all changes in #430 unnecessary (or redundant) because "LoadedMedias" was not necessary.

**Comment by chickentech** [comment]
@jeremyVignelles I'm still getting access violation on program close and garbage collection.

**Comment by jeremyVignelles** [comment]
@chickentech : does that happen only on a specific stream? Are you able to make a minimal project that reproduces the issue?

**Comment by dilandau2001** [comment]
Please. Try with the code of my last pull that is still not merged

**Comment by openlisp** [comment]
3.0.0-develop322 - still happening sometimes when Application.Current.Shutdown(); is called. Calling Dispose before is doable but not really handy because there could be more VLC players in a same time initialized in different places. The only way to close them at certain time  that i can see is to implement TWO-Way Publisher-Subscriber schema and on MainWindow_OnClosing event publish Dispose request with await on response and then continue with  closing after all Dispose action are finished.

**Comment by jeremyVignelles** [comment]
@openlisp :Can you open a separate issue with repro steps so that I can track your specific issue.
Can you also tell me with which video you are trying?
